# Generated by Django 5.2.8 on 2025-11-20 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
